"""empty message

Revision ID: 0c09be888801
Revises: e956ead3ced7
Create Date: 2024-01-25 23:51:48.411171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c09be888801'
down_revision = 'e956ead3ced7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
